#!/usr/bin/env python3
"""
gen_font.py -- rasterize PIL's built-in bitmap font into a C header.

Emits components/eye_core/eye_font.h: ASCII 32..127 in a fixed WxH cell,
one byte per row (bit7 = leftmost pixel). Regenerate with:
    python tools/gen_font.py
"""

import os

from PIL import Image, ImageDraw, ImageFont

CELL_W, CELL_H = 8, 12
FIRST, LAST = 32, 127

OUT = os.path.join(os.path.dirname(__file__), "..",
                   "components", "eye_core", "eye_font.h")


def rasterize(ch, font):
    # Draw at a fixed origin -- PIL's built-in font keeps its own baseline,
    # so no per-glyph repositioning (that misplaces '.', ',', etc.).
    out = Image.new("L", (CELL_W, CELL_H), 0)
    d = ImageDraw.Draw(out)
    d.text((1, 0), ch, fill=255, font=font)
    rows = []
    px = out.load()
    for yy in range(CELL_H):
        b = 0
        for xx in range(CELL_W):
            if px[xx, yy] > 96:
                b |= 0x80 >> xx
        rows.append(b)
    return rows


def main():
    font = ImageFont.load_default()
    lines = []
    lines.append("/* Generated by tools/gen_font.py -- do not edit by hand. */")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#define EYE_FONT_W      %d" % CELL_W)
    lines.append("#define EYE_FONT_H      %d" % CELL_H)
    lines.append("#define EYE_FONT_FIRST  %d" % FIRST)
    lines.append("#define EYE_FONT_LAST   %d" % LAST)
    lines.append("")
    lines.append("/* One byte per row, bit7 = leftmost pixel. Index: (ch - EYE_FONT_FIRST). */")
    lines.append("static const uint8_t eye_font[%d][%d] = {" %
                 (LAST - FIRST + 1, CELL_H))
    for code in range(FIRST, LAST + 1):
        ch = chr(code) if code < 127 else " "
        rows = rasterize(ch, font)
        body = ",".join("0x%02X" % b for b in rows)
        name = ch if (32 < code < 127 and ch not in "\\") else "0x%02X" % code
        lines.append("    {%s}, /* %s */" % (body, name))
    lines.append("};")
    lines.append("")
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote", os.path.normpath(OUT), "(%d glyphs, %dx%d)" %
          (LAST - FIRST + 1, CELL_W, CELL_H))


if __name__ == "__main__":
    main()
